#define FILE_TRANSFER 214
#define FILE_TRANSFER_STATUS 215
#define PAKE_ROUND_REQUEST 216
#define PAKE_ROUND_RESPONSE 217
#define KEY_CONFIRM_REQUEST_MESSAGE 218
#define KEY_CONFIRM_RESPONSE_MESSAGE 219
#define SHOW_NUMPAD_CMD 220
#define CGM_SOFTWARE_STATUS_REQ 234
#define CGM_SOFTWARE_STATUS_TE 235
#define CLEAR_KEY_STORAGE_REQ 237

#define USB_PACKET_DELIMITER 0x55
#define USB_MESSAGE_HEADER_SIZE 3
#define USB_CHECKSUM_SIZE 2
#define USB_TIMESTAMP_SIZE 4
#define SHOW_NUMPAD_PAYLOAD_SIZE 1
#define LEN_JPAKE_PHASE_BYTES 165